### PR TITLE
WIP: Support flowdock, team-based routing, small fixes

### PR DESCRIPTION
**Pull request by nabadger**
Hey,

This is a bit of a huge PR so I understand if you don't want it :) 

It might be of use to you still, so any comments welcome, or just take any bits you are interested in.

Essentially it:

- Adds a yaml configuration file to support multiple notification methods (I call them receivers)
- Adds 3 new annotations 
  - `kube-lookout/enabled`: Only notify if True
  - `kube-lookout/team`: Maps to a 'team', which is essentially a channel/token combination
  - `kube-lookout/receiver`: Maps to a receiver (flowdock/slack) 
- Deal with the case where no pods come up (should go into degradation state)
- Readme updates
- Update example manifests so that credentials are handled in a Secret resource type
- Default to a kube-lookout namespace (I'm not sure it's very common to populate kube-system by default)
- Move to pipenv and bump latest packages (because I couldn't get pinned packages to work)
- Move to deb-slim (just a personal preference here as we tend to run into issues with python/alpine in the past).

I still need to add tests for flowdock.

### CODE REVIEW

**Comment by nabadger** [comment]
Haha yeah no worries

**Comment by dmarkey** [comment]
The build doesnt pass :(

**Comment by nabadger** [comment]
I'll take a look at that :)

**Comment by antonblr** [comment]
> The build doesnt pass :(

Perhaps need to update `.travis.yml` with: 
```
install:
  - 'pip install pipenv'
  - 'pipenv install'
```

**Comment by nabadger** [comment]
I think these changes are too big for a PR at the moment.

I'll close this and think about creating a smaller set of PR's.

**Pull request closed without merging**
